config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :groups
#root 'welcome#index'
root 'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user! , only: [:new]
  
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.save

    redirect_to groups_path
  end

def update
  @group=Group.find(params[:id])

  if @group.update(group_params)
    redirect_to groups_path, notice: "Update Success"
  else
    render :edit
  end
end

def destroy
  @group=Group.find(params[:id])
  @group.destroy
  flash[:alert]="Group deleted"
  redirect_to groups_path
end
  private

  def group_params
    params.require(:group).permit(:title, :description)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
    flash[:alert] = "晚安！该睡了！"
    flash[:warning] = "这是 warning 信息！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>
<!-- 以上部分，不需要记忆 -->

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 1012</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("登录", '#') %>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- 以上部分，不需要记忆 -->

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
<div class="form-group">
    <div class="form-group string optional">
      <%= f.input :title, input_html: {class: "form-control"} %>
      <%= f.input :description, input_html: {class: "form-control"} %>
    </div>
  </div>
  <%=f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submiting..."} %>

<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑讨论版</h2>

  <hr>
  <%= form_for @group do |f| %>

   标题
  <%= f.text_field :title %>
  <br>
   叙述
  <br>
  <%=f.text_area :description %>
  <br>

  <%=f.submit "Submit", :disable_with => 'Submiting...' %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
        <td>Creator</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td><%= group.user.email %></td>
          <td>
            <% if current_user && current_user == group.user %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class = "col-md-4 col-md-offset-4">
  <h2>新增讨论板</h2>

  <hr>
<%= form_for @group do |f| %>

 标题
<%= f.text_field :title %>
<br>
 叙述
<br>
<%=f.text_area :description %>
<br>

<%=f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>

</div>

app/views/groups/show.html.erb
<div class = "col-md-12">
  <div class="group">
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @group.title %></h2>
  <p><%=@group.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails1012</title>
    <%= csrf_meta_tags %>

          <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>

      <body>

          <div class="container-fluid">
              <%= render "common/navbar" %>
              <%= render "common/flashes" %>
              <%= yield %>
          </div>

          <%= render "common/footer" %>

      </body>
  </html>

app/views/welcome/index.html.erb
<h1> hello world! </h1>